/**
 * Differential oracle (beekem-core §11.1, doctrine #4): replay the Rust
 * `beekem` crate's scenarios and byte-compare below the PcsKey seam.
 * Vectors: test-vectors/beekem-oracle.json (generated by the beekem-vectors
 * Rust harness against the keyhive clone @ 2026-07-09).
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { BeeKem } from '../src/tree.js';
import { ShareKeyMap, shareNodeKey } from '../src/keys.js';
import {
  deriveSymmetricKey,
  ratchetForward,
  shareKeyOf,
  type Csprng,
} from '../src/keyhive.js';
import { encryptSecret, tryEncrypterDecrypt } from '../src/encrypted.js';
import { bytesToHex, hexToBytes } from '../src/bytes.js';

const vectors = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('../../../test-vectors/beekem-oracle.json', import.meta.url)),
    'utf8',
  ),
);

/** Throwaway-pair randomness never affects root secrets; any stream works. */
const rng: Csprng = (n) => {
  const out = new Uint8Array(n);
  for (let i = 0; i < n; i++) out[i] = (i * 89 + 17) & 0xff;
  return out;
};

interface VecMember {
  id: string;
  initialSk: string;
}

function setup(members: VecMember[], docId: string): [BeeKem, ShareKeyMap[], Uint8Array[]] {
  const ids = members.map((m) => hexToBytes(m.id));
  const maps = members.map((m) => {
    const sks = new ShareKeyMap();
    const sk = hexToBytes(m.initialSk);
    sks.insert(shareKeyOf(sk), sk);
    return sks;
  });
  const tree = new BeeKem(hexToBytes(docId), ids[0]!, shareKeyOf(hexToBytes(members[0]!.initialSk)));
  for (let i = 1; i < members.length; i++) {
    tree.pushLeaf(ids[i]!, shareNodeKey(shareKeyOf(hexToBytes(members[i]!.initialSk))));
  }
  return [tree, maps, ids];
}

describe('differential oracle vs the Rust beekem crate', () => {
  for (const scenario of vectors.scenarios) {
    it(`scenario ${scenario.name}: root secrets match byte-for-byte`, () => {
      const [tree, maps, ids] = setup(scenario.members, scenario.docId);
      for (const step of scenario.steps) {
        const m = step.member as number;
        const newSk = hexToBytes(step.newLeafSk);
        maps[m]!.insert(shareKeyOf(newSk), newSk);
        const [root] = tree.encryptPath(ids[m]!, shareKeyOf(newSk), maps[m]!, rng);
        expect(bytesToHex(root)).toBe(step.expectRootSecret);
        // Every member's derived root matches the oracle too.
        for (let i = 0; i < ids.length; i++) {
          expect(bytesToHex(tree.decryptTreeSecret(ids[i]!, maps[i]!))).toBe(
            step.expectRootSecret,
          );
        }
      }
    });
  }

  it('concurrent scenario: conflict merge + resolution root matches', () => {
    const c = vectors.concurrent;
    const [treeA, mapsA, idsA] = setup(c.members, c.docId);
    const [treeB, mapsB, idsB] = setup(c.members, c.docId);
    const skA = hexToBytes(c.aUpdaterSk);
    mapsA[0]!.insert(shareKeyOf(skA), skA);
    const [, pathA] = treeA.encryptPath(idsA[0]!, shareKeyOf(skA), mapsA[0]!, rng);
    const skB = hexToBytes(c.bUpdaterSk);
    mapsB[3]!.insert(shareKeyOf(skB), skB);
    const [, pathB] = treeB.encryptPath(idsB[3]!, shareKeyOf(skB), mapsB[3]!, rng);
    treeA.applyPath(pathB);
    treeB.applyPath(pathA);
    expect(treeA.hasRootKey()).toBe(false);
    const skR = hexToBytes(c.resolverSk);
    mapsA[1]!.insert(shareKeyOf(skR), skR);
    const [root] = treeA.encryptPath(idsA[1]!, shareKeyOf(skR), mapsA[1]!, rng);
    expect(bytesToHex(root)).toBe(c.expectRootSecret);
    for (const i of [0, 1]) {
      expect(bytesToHex(treeA.decryptTreeSecret(idsA[i]!, mapsA[i]!))).toBe(c.expectRootSecret);
    }
  });

  it('cipher samples: encrypt_secret bytes (Siv nonce + XChaCha ct) match exactly', () => {
    const s = vectors.cipherSamples.encryptSecret;
    const enc = encryptSecret(
      hexToBytes(s.docId),
      hexToBytes(s.secret),
      hexToBytes(s.sk),
      hexToBytes(s.pairedPk),
    );
    expect(bytesToHex(enc.nonce)).toBe(s.nonce);
    expect(bytesToHex(enc.ciphertext)).toBe(s.ciphertext);
    // And the encrypter-side decrypt round-trips the Rust ciphertext.
    const dec = tryEncrypterDecrypt(
      { nonce: hexToBytes(s.nonce), ciphertext: hexToBytes(s.ciphertext), pairedPk: hexToBytes(s.pairedPk) },
      hexToBytes(s.sk),
    );
    expect(bytesToHex(dec)).toBe(s.secret);
  });

  it('cipher samples: ratchet_forward / derive_symmetric_key / share_key match', () => {
    const cs = vectors.cipherSamples;
    expect(bytesToHex(ratchetForward(hexToBytes(cs.ratchetForward.in)))).toBe(cs.ratchetForward.out);
    expect(
      bytesToHex(deriveSymmetricKey(hexToBytes(cs.deriveSymmetricKey.sk), hexToBytes(cs.deriveSymmetricKey.pk))),
    ).toBe(cs.deriveSymmetricKey.out);
    expect(bytesToHex(shareKeyOf(hexToBytes(cs.shareKeyOf.in)))).toBe(cs.shareKeyOf.out);
  });
});
